services:
  nextjs-1:
    build: .
    expose:
      - "3000" # Expose inside the Docker network

  nextjs-2:
    build: .
    expose:
      - "3000"

  nextjs-3:
    build: .
    expose:
      - "3000"

  nextjs-4:
    build: .
    expose:
      - "3000"

  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "8000:8000" # Expose only Nginx to the host
    depends_on:
      - nextjs-1
      - nextjs-2
      - nextjs-3
      - nextjs-4
